# Generated by Django 5.1.4 on 2026-08-27 16:26

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document_received', 'Document received'), ('duplicate_submission_ignored', 'Duplicate submission ignored'), ('job_enqueued', 'Job enqueued'), ('processing_started', 'Processing started'), ('extraction_succeeded', 'Extraction completed'), ('attempt_failed', 'Attempt failed'), ('retry_scheduled', 'Processing retried'), ('review_required', 'Result requires review'), ('result_accepted', 'Result accepted'), ('review_approved', 'Review approved'), ('review_rejected', 'Review rejected'), ('processing_failed', 'Processing failed permanently'), ('duplicate_execution_ignored', 'Duplicate execution ignored'), ('job_recovered', 'Stale job recovered'), ('manual_retry_requested', 'Manual retry requested')], max_length=48)),
                ('message', models.TextField()),
                ('attempt', models.PositiveIntegerField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('actor', models.CharField(blank=True, help_text="worker id, 'api', or 'reviewer:<name>'.", max_length=128)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_reference', models.CharField(blank=True, help_text='Caller supplied reference, e.g. an email id. Informational only.', max_length=255)),
                ('input_format', models.CharField(choices=[('json', 'JSON'), ('text', 'Text')], max_length=8)),
                ('raw_text', models.TextField(help_text='Exactly what was submitted, byte for byte.')),
                ('raw_payload', models.JSONField(blank=True, help_text='Parsed payload when the submission was valid JSON.', null=True)),
                ('content_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('forced_outcome', models.CharField(blank=True, help_text='Test hook: pins the simulated AI service to a specific outcome.', max_length=32)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('retry_scheduled', 'Retry scheduled'), ('review_required', 'Review required'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='received', max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Extraction attempts consumed so far.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('run_after', models.DateTimeField(db_index=True, help_text='Worker ignores this job until now() passes this point.')),
                ('locked_by', models.CharField(blank=True, max_length=128)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('run_after', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='result', serialize=False, to='documents.document')),
                ('attempt', models.PositiveIntegerField(help_text='Attempt that produced this result.')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField()),
                ('needs_review', models.BooleanField(db_index=True, default=True)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('raw_extraction', models.JSONField(blank=True, default=dict, help_text='Untouched response from the extraction service, kept for audit.')),
                ('extracted_at', models.DateTimeField()),
                ('review_action', models.CharField(blank=True, max_length=16)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('corrections', models.JSONField(blank=True, default=dict, help_text='Field level edits applied by the reviewer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='documents_d_status_64808e_idx'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.document'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.document'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='documents.processingjob'),
        ),
        migrations.AddConstraint(
            model_name='extractionresult',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__isnull', True), ('subtotal__gte', 0), _connector='OR'), name='extraction_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='extractionresult',
            constraint=models.CheckConstraint(condition=models.Q(('tax__isnull', True), ('tax__gte', 0), _connector='OR'), name='extraction_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='extractionresult',
            constraint=models.CheckConstraint(condition=models.Q(('total__isnull', True), ('total__gte', 0), _connector='OR'), name='extraction_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='extractionresult',
            constraint=models.CheckConstraint(condition=models.Q(('total__isnull', True), ('subtotal__isnull', True), ('tax__isnull', True), ('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('tax'))), _connector='OR'), name='extraction_total_matches_components'),
        ),
        migrations.AddConstraint(
            model_name='extractionresult',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='extraction_confidence_in_range'),
        ),
        migrations.AddConstraint(
            model_name='extractionresult',
            constraint=models.UniqueConstraint(condition=models.Q(('needs_review', False)), fields=('vendor_name', 'invoice_number'), name='unique_accepted_invoice_per_vendor'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'run_after'], name='documents_p_status_88accb_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('document',), name='unique_live_job_per_document'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['document', 'created_at'], name='documents_a_documen_ca594f_idx'),
        ),
    ]
